name: Create a release branch
on: [workflow_dispatch]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: hashicorp/actions-create-release-branch@v1
        with:
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
